### ISSUE TITLE
The paths are in unix format and will not work in windows out of box

### ISSUE THREAD

**Issue by nithyasharabheshwara** [tristanjl/netbeans-externalcommands#1]
I tried to use your plugin, but the ${FilePath} variable seems to be in Unix format, which is not going to work with windows.
-----
Aside : 
You might want to look at this, it somehow still works in NetBeans 12 even after almost 10 years of release. 
http://plugins.netbeans.org/plugin/676/path-tools
( depends on http://137.254.56.27/nexus/content/groups/netbeans/org/netbeans/api/org-jdesktop-layout/RELEASE65/ )

**Comment by tristanjl** [comment]
That sounds like an interesting plugin - would be good to see that be re-released on the current plugin portal.

I've updated the plugin with backslashes on Windows when using ${FilePath}. The new version has been pushed and is just awaiting verification.

**Comment by nithyasharabheshwara** [comment]
Thanks for the quick fix. The path-tools plugin is abandoned. Why don't you merge the features (or the codebase itself) in your project, as path-tools is quite similar to what you are doing, and it still works (just some UI issue if u have a custom there) in Netbeans 12.

**Comment by tristanjl** [comment]
It doesn't look like the source is available. I guess you could look at decompiling it (unsure of legality though) - but it might be worth looking into re-creating it as a separate plugin.

**Comment by nithyasharabheshwara** [comment]
I think he is the author : https://github.com/sandipchitale

**Comment by nithyasharabheshwara** [comment]
> It doesn't look like the source is available. I guess you could look at decompiling it (unsure of legality though) - but it might be worth looking into re-creating it as a separate plugin.

The sources seem to be available here > http://hg.netbeans.org/main/contrib/file/tip/pathtools
